# SurfaceDuoPkg CI build on VSTS

trigger:
  branches:
    include:
    - main
  paths:
    exclude:
    - README.md
    - LICENSE

pool:
  vmImage: 'ubuntu-latest'
  
steps:
- script: sudo apt update 
  displayName: 'Update APT sources'

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.10'
    architecture: 'x64'
  displayName: Install correct Python

- script: sudo apt install -y uuid-dev clang llvm gcc-aarch64-linux-gnu
  displayName: 'Install VSTS dependencies'

- script: export CLANG38_BIN=/usr/lib/llvm-38/bin/ && export CLANG38_AARCH64_PREFIX=aarch64-linux-gnu-
  displayName: 'Setup CLANG environment'

- script: pip install --upgrade -r ./pip-requirements.txt
  displayName: 'Install Python dependencies'

- script: chmod +x ./build_uefi_epsilon.sh && ./build_uefi_epsilon.sh
  displayName: 'UEFI build (Epsilon)'

- script: chmod +x ./build_uefi_zeta.sh && ./build_uefi_zeta.sh
  displayName: 'UEFI build (Zeta)'

- script: chmod +x ./build_boot_images.sh && ./build_boot_images.sh
  displayName: 'UEFI boot image build'

# Publish UEFI (1 target)
- task: PublishBuildArtifacts@1
  displayName: 'Publish SM8150 UEFI build (Surface Duo 1)'
  inputs:
    pathtoPublish: ./ImageResources/Epsilon/uefi.img
    artifactName: SM8150 UEFI (Surface Duo 1)

# Publish FD (1 target)
- task: PublishBuildArtifacts@1
  displayName: 'Publish SM8150 FD build (Surface Duo 1)'
  inputs:
    pathtoPublish: ./Build/SurfaceDuo1-AARCH64/DEBUG_CLANG38/FV/SM8150_EFI.fd
    artifactName: SM8150 FD (Surface Duo 1)

# Publish UEFI (1 target)
- task: PublishBuildArtifacts@1
  displayName: 'Publish SM8350 UEFI build (Surface Duo 2)'
  inputs:
    pathtoPublish: ./ImageResources/Zeta/uefi.img
    artifactName: SM8350 UEFI (Surface Duo 2)

# Publish FD (1 target)
- task: PublishBuildArtifacts@1
  displayName: 'Publish SM8350 FD build (Surface Duo 2)'
  inputs:
    pathtoPublish: ./Build/SurfaceDuo2-AARCH64/DEBUG_CLANG38/FV/SM8350_EFI.fd
    artifactName: SM8350 FD (Surface Duo 2)